Repository DDSS-FE/DDuck-SSang, pull requests merged in 2022-02, with the labels that each got.

#13 [Feat] #8 market-detail-layout
  components/Chart/Chart.module.scss
  components/Chart/index.tsx
  components/DetailHeader/DetailHeader.module.scss
  components/DetailHeader/index.tsx
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/IconButton/IconButton.module.scss
  components/IconButton/index.tsx
  components/Logo/Logo.module.scss
  components/Logo/index.tsx
  components/StockDetail/StockDetail.module.scss
  components/StockDetail/index.tsx
  components/StockInfoList/StockInfoList.module.scss
  components/StockInfoList/index.tsx
  next.config.js
  pages/_app.tsx
  pages/market/Market.module.scss
  pages/market/[id].tsx
Labels: style 🎨

#19 [Feat] Apply dark-mode
  components/BorderButton/BorderButton.module.scss
  components/Chart/Chart.module.scss
  components/DetailHeader/DetailHeader.module.scss
  components/DetailHeader/index.tsx
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/IconButton/IconButton.module.scss
  components/IconButton/index.tsx
  components/NavBar/NavBar.module.scss
  components/StockDetail/StockDetail.module.scss
  components/StockDetail/index.tsx
  hooks/useAxios.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/market/Market.module.scss
  pages/more/index.tsx
  pages/more/more.module.scss
  styles/Home.module.scss
  styles/globals.scss
  styles/theme.scss
  yarn.lock
Labels: enhancement 🚀, style 🎨

#21 [Feat] #16 Chart Team2
  components/Chart/ChartCanvas.tsx
  components/Chart/index.tsx
  package.json
  utils/drawChart.ts
  utils/renderChart.ts
Labels: enhancement 🚀, canvas chart 🖼

#26 Feat/#25/chart x y axis
  components/Chart/ChartCanvas.module.scss
  components/Chart/ChartCanvas.tsx
  components/Chart/index.tsx
  components/MarketDetail/MarketDetail.module.scss
  utils/config.ts
  utils/renderChart.ts
  yarn.lock
Labels: enhancement 🚀, canvas chart 🖼

#29 [Refactor] Separate chart class
  components/Chart/ChartCanvas.tsx
  styles/theme.scss
  utils/chart/chart.ts
  utils/chart/charts.ts
  utils/chart/index.ts
  utils/chart/types.ts
  utils/formatDate.ts
  utils/renderChart.ts
Labels: refactoring 🔩

#30 [Refactor] Absolute Imports and Module path aliases
  components/DetailNav/index.tsx
  next.config.js
  pages/404.tsx
  tsconfig.json
Labels: refactoring 🔩

#34 [Feat] line chart
  components/Chart/ChartCanvas.tsx
  styles/globals.scss
  utils/chart/chart.ts
  utils/chart/charts.ts
  utils/chart/index.ts
  utils/chart/types.ts
Labels: enhancement 🚀, canvas chart 🖼, refactoring 🔩

#37 Feat/#27/chart info
  components/KeyInfo/index.tsx
  components/MarketDetail/index.tsx
  utils/config.ts
  utils/formatDate.ts
  utils/market/types.ts
Labels: enhancement 🚀, refactoring 🔩, external APIs 🛰

#39 [Chore] #38 jest, RTL setting
  .eslintrc.json
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  yarn.lock
Labels: config :wrench:

#41 [Bug] #40 Path setup failed
  jest.config.js
Labels: bug 🐛

#49 [Feat] #35 chart period button
  components/Chart/Chart.module.scss
  components/Chart/ChartCanvas.tsx
  components/Chart/__tests__/index.test.tsx
  components/Chart/index.tsx
  components/PeriodButton/PeriodButton.module.scss
  components/PeriodButton/__tests__/index.test.tsx
  components/PeriodButton/index.tsx
  hooks/useAxios.tsx
  utils/chart/chart.ts
  utils/chart/types.ts
Labels: enhancement 🚀, canvas chart 🖼, refactoring 🔩

#52 [Feat] add chart type toggle
  components/Chart/Chart.module.scss
  components/Chart/ChartCanvas.tsx
  components/Chart/index.tsx
  components/ChartTypeToggleButton/ChartTypeToggleButton.module.scss
  components/ChartTypeToggleButton/__tests__/index.test.tsx
  components/ChartTypeToggleButton/index.tsx
  components/PeriodButton/PeriodButton.module.scss
  components/PeriodButton/index.tsx
  hooks/useAxios.tsx
  public/candleIcon.svg
  public/lineIcon.svg
  styles/assets/ic-check-box.svg
  utils/chart/types.ts
Labels: enhancement 🚀, canvas chart 🖼

#56 [Feat] market tab
  components/DetailNav/index.tsx
  components/MarketDetail/index.tsx
  components/MarketInfoList/MarketInfoList.module.scss
  components/MarketInfoList/MarketInfoListItem.tsx
  components/MarketInfoList/index.tsx
  components/NavBar/index.tsx
  pages/market/[category]/[id].tsx
  pages/market/[category]/index.tsx
Labels: enhancement 🚀

#55 [Feat] #54 news page
  components/NewsDetail/NewsDetail.module.scss
  components/NewsDetail/index.tsx
  components/NewsDetailHeader/NewsDetailHeader.module.scss
  components/NewsDetailHeader/index.tsx
  components/NewsHeadline/NewsHeadline.module.scss
  components/NewsHeadline/index.tsx
  pages/api/imagefetcher.ts
  pages/news/[id].tsx
  pages/news/[id]/index.tsx
  pages/news/index.tsx
  pages/news/news.module.scss
  utils/config.ts
  yarn.lock
Labels: enhancement 🚀

#61 [Fix] newspage bugs fix
  pages/news/[id]/index.tsx
  pages/news/index.tsx
Labels: bug 🐛

#73 [Fix] #72 remove key info in crypto market
  components/KeyInfo/index.tsx
  components/MarketDetail/index.tsx
  pages/market/[category]/[symbol].tsx
Labels: fix 🛠
