Repository DDSS-FE/DDuck-SSang, pull requests merged in 2022-03, with the labels that each got.

#69 [Feat] Market Tab Done
  components/MarketDetailHeader/__tests__/index.test.tsx
  components/MarketDetailHeader/index.tsx
  components/MarketInfoList/MarketInfoList.module.scss
  components/MarketInfoList/MarketInfoListItem.tsx
  components/MarketInfoList/__tests__/index.test.tsx
  utils/formatDate.ts
Labels: enhancement 🚀

#74 [Feat] strapi v4 custom server connections
  components/Chart/index.tsx
  components/FormDialog.tsx
  components/KeyInfo/__tests__/index.test.tsx
  components/KeyInfo/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/more/index.tsx
  pages/news/news.module.scss
  store/index.ts
  store/modules/index.ts
  store/modules/user/index.ts
  store/modules/user/useUser.ts
  utils/config.ts
  yarn.lock
Labels: external APIs 🛰, config :wrench:

#77 [Feat] #68 signin signup component
  components/Button/Button.module.scss
  components/Button/index.tsx
  components/Form/Form.module.scss
  components/Form/__tests__/SignIn.test.tsx
  components/Form/__tests__/SignUp.test.tsx
  components/Form/index.tsx
  styles/globals.scss
Labels: enhancement 🚀, test

#80 [Feat] #75 more page component
  pages/more/index.tsx
Labels: enhancement 🚀, style 🎨

#82 [Feat] Adds a watchlist to the redux-toolkit
  components/FormDialog.tsx
  components/StockList/StockListItem.tsx
  components/StockList/index.tsx
  jest.config.ts
  package-lock.json
  package.json
  pages/market/[category]/[symbol].tsx
  store/index.ts
  store/modules/index.ts
  store/modules/user/index.ts
  store/modules/watchlist/__tests__/reducer.test.ts
  store/modules/watchlist/useWatchlist.ts
  store/modules/watchlist/watchlistSlice.ts
  yarn.lock
Labels: enhancement 🚀, refactoring 🔩

#84 [Feat] #83 form component test code refactoring
  components/Form/__tests__/SignIn.test.tsx
  components/Form/__tests__/SignUp.test.tsx
  jest.config.ts
Labels: refactoring 🔩, test

#89 [Feat] Cover `addWatchlist` with debounce and setAddStatus
  components/FormDialog.tsx
  package-lock.json
  package.json
  pages/market/[category]/[symbol].tsx
  store/modules/watchlist/useWatchlist.ts
  yarn.lock
Labels: enhancement 🚀, fix 🛠

#92 [Feat] Get current price crypto and stock through websockets
  components/MarketInfoList/MarketInfoList.module.scss
  components/MarketInfoList/MarketInfoListItem.tsx
  components/MarketInfoList/__tests__/index.test.tsx
  components/MarketInfoList/index.tsx
  package-lock.json
  package.json
  pages/market/[category]/index.tsx
  utils/formatDate.ts
  utils/quote.ts
  utils/stockFetcher.ts
  yarn.lock
Labels: enhancement 🚀, refactoring 🔩

#94 [Docs] #93 update readme
  README.md
Labels: documentation 📝

#95 [Feat] Add playwright e2e testing
  components/Chart/Chart.module.scss
  components/Chart/ChartCanvas.tsx
  components/MarketInfoList/MarketInfoListItem.tsx
  components/StockList/index.tsx
  package-lock.json
  package.json
  pages/market/[category]/[symbol].tsx
  pages/watchlist/index.tsx
  playwright.config.ts
  store/modules/watchlist/useWatchlist.ts
  styles/_variables.scss
  styles/globals.scss
  test-results/tests-watchlist-Watchlist-관심목록-없음-확인---상세페이지에서-AAPL-추가---관심목록에서-AAPL-확인---삭제---관심목록-확인-Mobile-Safari/video.webm
  test-results/tests-watchlist-Watchlist-마켓-상세페이지에서-관심목록-추가-삭제-버튼-토글되는지-확인-Mobile-Safari/video.webm
  tests/watchlist.spec.ts
  yarn.lock
Labels: test

#97 [Feat] #96 change form and news layout
  components/Form/Form.module.scss
  components/Form/index.tsx
  components/NewsInfoList/index.tsx
  components/NewsInfoListItem/NewsInfoListItem.module.scss
  components/NewsInfoListItem/index.tsx
  package-lock.json
  yarn.lock
Labels: enhancement 🚀, style 🎨

#99 [Feat] Render real-time market data to the watchlist
  components/StockList/index.tsx
Labels: enhancement 🚀

#101 [Feat] change format of USDate to 24hours
  utils/formatDate.ts
Labels: enhancement 🚀, fix 🛠

#105 [Feat] show error message when market data is not available
  components/MarketInfoList/index.tsx
  styles/globals.scss
Labels: fix 🛠

#103 [Feat] #102 test automation
  .eslintignore
  .github/workflows/ci.yml
  README.md
  components/Form/__tests__/SignIn.test.tsx
  components/Form/__tests__/SignUp.test.tsx
  components/Form/index.tsx
  components/MarketInfoList/MarketInfoListItem.tsx
  components/MarketInfoList/__tests__/index.test.tsx
  components/StockList/__tests__/index.test.tsx
  components/StockList/index.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement 🚀
